### PR TITLE
Ignore compiled test file

### PR DESCRIPTION
**Pull request by joelpurra**

### CODE REVIEW

**Comment by thegecko** [comment]
What does this change do?

**Comment by joelpurra** [comment]
@thegecko: ignores the compiled test file used in the `valgrind` test.

https://github.com/tessel/node-usb/blob/v1.7.1/package.json#L42

**Comment by thegecko** [comment]
OK, could you add it to the root `.gitignore instead`?

**Review by thegecko — APPROVED** [review]
Thanks 👍

**Pull request merged**
