### PR TITLE
Bumps packages version in preparation for release.

### PR DESCRIPTION
**Pull request by MicahZoltu**
I'm hoping that CI is setup for this project and if this PR is merged then it will auto-release.  I'm currently blocked because I don't have the tooling required to compile this package from source on a target machine that is running NodeJS 14.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Any progress on this?  Is there anything else I can do to assist with getting a new version out with NodeJS 14 support?

**Comment by MicahZoltu** [comment]
I have made the necessary changes to get NodeJS 14 prebuilds working in Travis CI.  My hope is that this was what was keeping this PR from being merged and a new version deployed and now with these changes we can get a new version deployed.

Alternatively, if the build artifacts are merely added to GitHub then a new deploy is not needed.

**Comment by MicahZoltu** [comment]
Note to future readers: I have a fork of this project at `@zoltu/usb` which implements this change and thus works in NodeJS 14.  I have no real intention of maintaining it, but if all you need is to just get things working in NodeJS 14 then you can swap out with that version as a temporary work around until hopefully this gets merged and deployed at some point.

**Comment by thegecko** [comment]
Thanks @MicahZoltu 

The latest release moves to using Node-API, so it should now work with all Node.js versions >8

**Pull request closed without merging**
